development:
    :action_controller:
        :session:
          :secret:  <your secret session key here>
    :action_mailer:
        :delivery_method: :smtp
        :smtp_settings:
          :address: <your mail server here>
          :port: 25
          :authentication: plain
          :user_name: <your user name for the mail server here>
          :password: <your password for your mailserver here>
          :domain: <your domain here>
          :perform_deliveries: true
    :default_host: <your default host here>
    :bitly: <your bitly api key here for the sharing of content>
    :google_verify: <your google webmaster tools verification code here>
    :cron_job_code: <your secret cron job code goes here make this long and preferable a long hash >